//Given two strings s and t which consist of only lowercase letters.

//String t is generated by random shuffling string s and then
//add one more letter at a random position.

//Find the letter that was added in t.

//仍然是统计，找不同
public static char findTheDifference(String s, String t){
    int[] array = new int[26];
    for (int i=0; i<s.length(); i++) {
        array[s.charAt(i)-'a']++;
    }
    char temp = ' ';
    for (int i=0; i<t.length(); i++) {
        temp = t.charAt(i);
        if (array[temp-'a'] == 0) {
            break;
        }
        array[temp-'a']--;
    }
    return temp;
}




//一个更好的解法，我们可以将这个问题看作是，从一个每个元素都重复2次的string中找到
//找到一个只出现一个的char
    public char findTheDifference(String s, String t) {
		char res = t.charAt(0);
		for (int i = 1;i<t.length() ;i++ ) {
			res^=s.charAt(i-1);
			res^=t.charAt(i);
		}
		return res;
    }
